SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME FROM ANIMAL_OUTS AS A, ANIMAL_INS AS B
WHERE A.ANIMAL_ID=B.ANIMAL_ID AND (B.SEX_UPON_INTAKE IN ('Intact Male','Intact Female')) 
AND (A.SEX_UPON_OUTCOME NOT IN ('Intact Male','Intact Female')) ORDER BY A.ANIMAL_ID;